// NoteView.swift
// ClinicalAI — SOAP Note Display
//
// Shows the structured SOAP note generated by Claude after an encounter ends.
// The physician can read all five sections and copy the full note to the clipboard
// for pasting into their EHR system.
//
// Full inline editing and EHR export will be implemented in a future prompt.

import SwiftUI
import UIKit

struct NoteView: View {

    @State private var viewModel: NoteViewModel
    @State private var showCopiedBanner = false

    init(note: ClinicalNote) {
        _viewModel = State(wrappedValue: NoteViewModel(note: note))
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 0) {
                noteMetaHeader
                    .padding(.horizontal)
                    .padding(.top, 16)
                    .padding(.bottom, 20)

                Divider()

                VStack(alignment: .leading, spacing: 24) {
                    soapSection(
                        title: "Chief Complaint",
                        icon: "person.fill.questionmark",
                        text: viewModel.note.chiefComplaint
                    )
                    soapSection(
                        title: "History of Present Illness",
                        icon: "clock.arrow.circlepath",
                        text: viewModel.note.historyOfPresentIllness
                    )
                    soapSection(
                        title: "Physical Examination",
                        icon: "stethoscope",
                        text: viewModel.note.physicalExamFindings
                    )
                    soapSection(
                        title: "Assessment",
                        icon: "list.bullet.clipboard",
                        text: viewModel.note.assessment
                    )
                    soapSection(
                        title: "Plan",
                        icon: "checklist",
                        text: viewModel.note.plan
                    )
                }
                .padding(.horizontal)
                .padding(.vertical, 20)

                if viewModel.note.isEdited {
                    attestationFooter
                        .padding(.horizontal)
                        .padding(.bottom, 20)
                }
            }
        }
        .navigationTitle("Clinical Note")
        .navigationBarTitleDisplayMode(.large)
        .toolbar { toolbarContent }
        .overlay(alignment: .top) {
            if showCopiedBanner {
                copiedBanner
                    .transition(.move(edge: .top).combined(with: .opacity))
                    .padding(.top, 8)
            }
        }
        .animation(.spring(duration: 0.35), value: showCopiedBanner)
    }

    // MARK: - Note meta header

    private var noteMetaHeader: some View {
        HStack {
            VStack(alignment: .leading, spacing: 4) {
                Text("AI-Assisted Clinical Note")
                    .font(.subheadline.weight(.semibold))
                Text(viewModel.note.generatedAt, style: .date)
                    .font(.caption)
                    .foregroundStyle(.secondary)
                +
                Text(" at ")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                +
                Text(viewModel.note.generatedAt, style: .time)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            if viewModel.isDirty {
                Label("Reviewed", systemImage: "checkmark.seal.fill")
                    .font(.caption.weight(.medium))
                    .foregroundStyle(.green)
            } else {
                Label("Pending review", systemImage: "exclamationmark.triangle")
                    .font(.caption.weight(.medium))
                    .foregroundStyle(.orange)
            }
        }
    }

    // MARK: - SOAP section

    @ViewBuilder
    private func soapSection(title: String, icon: String, text: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Label(title, systemImage: icon)
                .font(.headline)
                .foregroundStyle(.primary)

            Text(text.isEmpty ? "—" : text)
                .font(.body)
                .foregroundStyle(text.isEmpty ? .tertiary : .secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
    }

    // MARK: - Attestation footer

    private var attestationFooter: some View {
        VStack(alignment: .leading, spacing: 4) {
            Divider()
                .padding(.bottom, 8)
            Text("This note was generated by ClinicalAI (AI-assisted) and reviewed and amended by the attending physician.")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
    }

    // MARK: - Copied banner

    private var copiedBanner: some View {
        HStack(spacing: 8) {
            Image(systemName: "doc.on.doc.fill")
            Text("Note copied to clipboard")
                .font(.subheadline.weight(.medium))
        }
        .padding(.horizontal, 20)
        .padding(.vertical, 10)
        .background(Color(.systemBackground).shadow(.drop(radius: 8)))
        .clipShape(Capsule())
    }

    // MARK: - Toolbar

    @ToolbarContentBuilder
    private var toolbarContent: some ToolbarContent {
        ToolbarItem(placement: .topBarTrailing) {
            Button {
                UIPasteboard.general.string = viewModel.plainTextForEHR
                showCopiedBanner = true
                Task {
                    try? await Task.sleep(for: .seconds(2))
                    showCopiedBanner = false
                }
            } label: {
                Label("Copy for EHR", systemImage: "doc.on.doc")
            }
        }
    }
}

// MARK: - Preview

#Preview {
    NavigationStack {
        NoteView(note: ClinicalNote(
            id: UUID(),
            encounterSessionId: UUID(),
            generatedAt: Date(),
            chiefComplaint: "Productive cough and fever for 3 days",
            historyOfPresentIllness: "52-year-old male with T2DM presenting with 3-day history of productive cough with yellow-green sputum, fever 38.9°C, and right-sided pleuritic chest pain.",
            physicalExamFindings: "Temp 38.6°C, HR 98, BP 138/84, RR 20, O2 sat 95%. Dullness to percussion right lower lobe. Crackles and bronchial breath sounds right lower lobe.",
            assessment: "1. Community-acquired pneumonia, right lower lobe (CURB-65 score 1).\n2. Type 2 diabetes mellitus.",
            plan: "1. Amoxicillin-clavulanate 875/125 mg PO BID × 5 days.\n2. Azithromycin 500 mg PO Day 1, then 250 mg Days 2–5.\n3. Follow-up 48–72 hours.",
            rawJSON: "{}",
            isEdited: false
        ))
    }
}
