// ClinicalNote.swift
// ClinicalAI — SOAP Note Data Model
//
// Represents the structured clinical note produced by Claude from a completed encounter.
// Follows the SOAP format standard in most clinical settings:
//
//   Subjective  — what the patient reports (chief complaint, history of present illness)
//   Objective   — what the physician observes (physical exam, including visual findings
//                 from the glasses photos)
//   Assessment  — the physician's diagnoses and clinical impression
//   Plan        — treatment, medications, follow-up, referrals
//
// Notes are encrypted at rest via EncryptionService. Raw field text must never be written
// to disk without first passing through EncryptionService.

import Foundation

// MARK: - ClinicalNote

/// A structured SOAP note generated by Claude from a completed encounter session.
///
/// Each of the five SOAP fields is stored as an independent string so the physician can
/// edit individual sections without affecting the others. The `rawJSON` field retains
/// Claude's original response for debugging and audit purposes.
///
/// After the physician reviews and optionally edits the note, it is exported as plain text
/// via `plainTextForEHR` for copy-paste into their EHR system.
struct ClinicalNote: Identifiable, Codable, Equatable {
    /// Unique identifier for this note.
    let id: UUID

    /// The `EncounterSession.id` this note was generated from.
    /// Use this to navigate from a note back to the encounter that produced it.
    let encounterSessionId: UUID

    /// Wall-clock time when Claude returned this note.
    let generatedAt: Date

    // MARK: SOAP fields

    /// The patient's primary reason for the visit, ideally in their own words.
    ///
    /// Example: "3-day history of productive cough and fever."
    var chiefComplaint: String

    /// Expanded narrative of the present illness — onset, character, severity, timing,
    /// aggravating/relieving factors, and associated symptoms.
    ///
    /// This is the "story" of the illness as Claude assembled it from the transcript.
    var historyOfPresentIllness: String

    /// Objective physical exam findings, including structured descriptions of any visual
    /// findings captured by the glasses during the encounter.
    ///
    /// Claude incorporates image-based findings (e.g., "erythematous rash noted on right
    /// forearm, approximately 3 cm, well-demarcated") alongside transcript-based observations.
    var physicalExamFindings: String

    /// The physician's clinical assessment: primary diagnosis, differential diagnoses,
    /// and overall clinical impression.
    ///
    /// Example: "1. Community-acquired pneumonia, right lower lobe. 2. Rule out pulmonary
    /// embolism given tachycardia."
    var assessment: String

    /// The treatment plan: medications with dosing, procedures, referrals, patient education,
    /// and scheduled follow-up.
    var plan: String

    // MARK: Raw source

    /// The raw JSON string returned by Claude before it was parsed into the SOAP fields above.
    ///
    /// Retained for debugging (e.g., if a field parses incorrectly) and for compliance audits
    /// that require the original AI output. Not shown to the physician during normal use.
    let rawJSON: String

    // MARK: Edit tracking

    /// `true` if the physician has modified any field after the AI generated this note.
    ///
    /// Displayed in the notes list so the physician can distinguish AI-only output from
    /// notes they have personally reviewed and amended. Also used during EHR export to
    /// include an appropriate attestation line.
    var isEdited: Bool
}

// MARK: - Plain-text EHR export

extension ClinicalNote {
    /// Returns the note formatted as a single plain-text string for copy-paste into an EHR.
    ///
    /// Section headers match the labels expected by most EHR free-text fields. Each section
    /// is separated by a blank line for readability. An attestation footer is appended when
    /// `isEdited` is `true` to indicate the physician reviewed and amended the AI output.
    ///
    /// Example output:
    /// ```
    /// CHIEF COMPLAINT
    /// 3-day history of productive cough and fever.
    ///
    /// HISTORY OF PRESENT ILLNESS
    /// Patient is a 45-year-old male who presents with...
    ///
    /// PHYSICAL EXAMINATION
    /// Vital signs stable. Lungs: decreased breath sounds right base...
    ///
    /// ASSESSMENT
    /// 1. Community-acquired pneumonia, right lower lobe.
    ///
    /// PLAN
    /// 1. Amoxicillin-clavulanate 875 mg PO BID x 7 days.
    /// 2. Follow up in 1 week or sooner if symptoms worsen.
    ///
    /// ---
    /// Note generated by ClinicalAI (AI-assisted) and reviewed by the attending physician.
    /// ```
    var plainTextForEHR: String {
        var sections = [
            "CHIEF COMPLAINT",
            chiefComplaint,
            "",
            "HISTORY OF PRESENT ILLNESS",
            historyOfPresentIllness,
            "",
            "PHYSICAL EXAMINATION",
            physicalExamFindings,
            "",
            "ASSESSMENT",
            assessment,
            "",
            "PLAN",
            plan,
        ]

        // Append an attestation footer so the receiving EHR provider knows this note
        // was AI-generated. When the physician has edited the note, the footer reflects that.
        sections += [
            "",
            "---",
            isEdited
                ? "Note generated by ClinicalAI (AI-assisted) and reviewed and amended by the attending physician."
                : "Note generated by ClinicalAI (AI-assisted). Pending physician review.",
        ]

        return sections.joined(separator: "\n")
    }
}
